name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build WebAssembly
        run: |
          cd wasm
          wasm-pack build --target no-modules
          # Remove the entire deploy/ directory to start fresh
          rm -rf deploy/
          mkdir deploy/
          # Copy static assets (HTML, CSS, JS) from the original deploy/
          cp -v deploy-template/* deploy/
          # Copy actual WASM and JS files from pkg/, avoiding symlinks
          cp -v pkg/*.js deploy/
          cp -v pkg/*.wasm deploy/
          # Copy the entire examples directory
          cp -r ../examples deploy/
          # Add .nojekyll
          touch deploy/.nojekyll
          ls -la deploy/  # Debug: Confirm files and directories
          ls -la deploy/examples/  # Debug: Confirm examples contents

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: wasm/deploy  # Deploy the contents of wasm/deploy